import { connect } from 'react-redux'
import Component from './component'
import {
  getWarningVideos,
  getWarningVideosDetail,
  getDensityPicture,
  getDensityPictureData,
  downloadWarningVideos,
  uploadAttach,
  getDeviceList,
  getFuzzyDeviceList,
  addDeviceToSystem,
  getDeviceDetails,
  getDeviceGroup,
  addGroup,
  editGroupName,
  deleteGroupName,
  editEquipmentName,
  moveEquipmentName,
  deleteDeviceByRelation,
  addDevGroup,
  getLogList,
  getUserList,
  deleteUserDevice,
  checkSecondPsw,
  addUserDevice,
  getRootDeviceGroup,
  addRootGroup,
  moveRootEquipmentName,
  deletRootGroupName,
  deleteGroupDevice,
  editRootGroup
} from 'store/modules/manager'

import { modifyPassword } from 'store/modules/login'

const mapDispatchToProps = {
  getWarningVideos,
  getWarningVideosDetail,
  getDensityPicture,
  getDensityPictureData,
  downloadWarningVideos,
  uploadAttach,
  getDeviceList,
  getFuzzyDeviceList,
  addDeviceToSystem,
  getDeviceDetails,
  getDeviceGroup,
  addGroup,
  editGroupName,
  deleteGroupName,
  editEquipmentName,
  moveEquipmentName,
  deleteDeviceByRelation,
  addDevGroup,
  getLogList,
  getUserList,
  modifyPassword,
  deleteUserDevice,
  checkSecondPsw,
  addUserDevice,
  getRootDeviceGroup,
  addRootGroup,
  moveRootEquipmentName,
  deletRootGroupName,
  deleteGroupDevice,
  editRootGroup
}

const mapStateToProps = (state) => ({
  warningVideos: state.manager.warningVideos,
  warningVideosDetail: state.manager.warningVideosDetail,
  densityPicture: state.manager.densityPicture,
  densityPictureData: state.manager.densityPictureData,
  deviceList: state.manager.deviceList,
  fuzzyDeviceList: state.manager.fuzzyDeviceList,
  deviceDetails: state.manager.deviceDetails,
  deviceGroup: state.manager.deviceGroup,
  logList: state.manager.logList,
  userList: state.manager.userList,
  rootDeviceGroup: state.manager.rootDeviceGroup,
})
export default connect(mapStateToProps, mapDispatchToProps)(Component)
